import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function renderScaleSet({ namespace = 'arc-runners', setName = 'arc-factory', githubConfigUrl, runnerGroup }) {
  let tpl = readFileSync(join(root, 'templates', 'arc-scaleset.yaml'), 'utf8');
  return tpl
    .replaceAll('__NAMESPACE__', namespace)
    .replaceAll('__SET_NAME__', setName)
    .replaceAll('__GITHUB_CONFIG_URL__', githubConfigUrl)
    .replaceAll('__RUNNER_GROUP__', runnerGroup || setName);
}

export function writeScaleSet(outDir, opts) {
  mkdirSync(outDir, { recursive: true });
  const p = join(outDir, 'arc-scaleset.yaml');
  writeFileSync(p, renderScaleSet(opts));
  return p;
}

export function kubectlOk() {
  return spawnSync('kubectl', ['version', '--client'], { stdio: 'ignore' }).status === 0;
}

export function helmOk() {
  return spawnSync('helm', ['version'], { stdio: 'ignore' }).status === 0;
}

export function helmInstructions(setName) {
  return [
    'ARC controller (run where your cluster admin works):',
    '  helm install arc oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller --namespace arc-systems --create-namespace',
    `  helm install ${setName} oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \\`,
    '    --namespace arc-runners --create-namespace \\',
    '    --set githubConfigUrl="https://github.com/<OWNER>" \\',
    '    --set githubConfigSecret=arc-github-secret \\',
    '    --set containerMode.type=dind \\',
    '    -f arc-scaleset.yaml   # generated by: npx wtfactory arc --org <OWNER>',
  ].join('\n');
}
